name: Deploy Process
inputs:
  AWS_S3_BUCKET:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_REGION:
    default: us-east-1
  SOURCE_DIR:
    default: dist
  artifact-name:
    default: build-artifact
    
runs:
  using: "composite"

  steps:
  - name: Download a Build Artifact
    uses: actions/download-artifact@v2.0.10
    with:
      name: ${{ inputs.artifact-name }}
      path: ${{ inputs.SOURCE_DIR }}
  - name: Deploy to S3
    uses: jakejarvis/s3-sync-action@master
    with:
      args: --acl public-read --delete
    env:
      AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ inputs.AWS_REGION }}
      SOURCE_DIR: ${{ inputs.SOURCE_DIR }}   
  - name: Smoke Test
    shell: bash
    run: curl -f http://${{ inputs.AWS_S3_BUCKET }}.s3-website-us-east-1.amazonaws.com/
