name: CICD Process
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      node-version: 12.x
      language: 'javascript'
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
          languages: ${{ env.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    - name: Yarn Install
      run: |
        yarn install
    - name: Staging Build
      run: |
        yarn build
    - name: Unit Tests
      run: |
        yarn test
    - name: Deploy to S3
      if: github.event_name != 'pull_request'
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'dist'
